import type { PaperclipPluginManifestV1 } from "@paperclipai/plugin-sdk";
const fleet = { type: "object", additionalProperties: false, properties: { fleetId: { type: "string" } }, required: ["fleetId"] };
export const fleetTools: NonNullable<PaperclipPluginManifestV1["tools"]> = [
  { name: "support_start_fleet_check", displayName: "Check office computers for issues", requiredUserPermission: "support:diagnose", executionTimeoutMs: 60_000, writes: true,
    description: "Use when asked whether office devices have visible issues or to check the network for problems. Discover the saved company network and plan a durable read-only Windows health check for up to 10 permitted targets (maxDevices can be 1–20). Discovery alone cannot answer health questions. Returns a fleetId and progress; call support_continue_fleet_check until pending is zero, reporting real updates. Optional targets restrict the check to full permitted names from current discovery. Printers/appliances with no supported Windows access are explicitly skipped, never called healthy. No repairs or credentials in chat. Resumes an existing active check in this person's conversation.",
    parametersSchema: { type: "object", additionalProperties: false, properties: { networkId: { type: "string" }, maxDevices: { type: "integer", minimum: 1, maximum: 20 }, targets: { type: "array", minItems: 1, maxItems: 20, items: { type: "string" } } } } },
  { name: "support_continue_fleet_check", displayName: "Investigate the next office computer", requiredUserPermission: "support:diagnose", executionTimeoutMs: 210_000, writes: true,
    description: "Continue this person's durable fleet check. Rechecks permission and saved company access, opens a conversation-owned case and runs one read-only health snapshot, saving findings and partial/unavailable checks. Continue while pending remains; never substitute discovery ports for diagnostics or automatically repair. Review failed/interrupted results, report progress, and use recorded caseId for deeper diagnosis or a separately authorized fix.", parametersSchema: fleet },
  { name: "support_get_fleet_check", displayName: "Review fleet check progress", requiredUserPermission: "support:diagnose",
    description: "Read this person's fleet check after an interrupted reply, including actual diagnostic findings, case IDs, counts and skipped devices. No command runs. Historical results do not prove present health.", parametersSchema: fleet },
  { name: "support_stop_fleet_check", displayName: "Stop the fleet check", requiredUserPermission: "support:diagnose", writes: true,
    description: "Stop starting further devices in this person's fleet check. A remote diagnostic already running may finish; this cannot reliably interrupt its process. Saved observations remain available.", parametersSchema: fleet },
];
