import type { PaperclipPluginManifestV1 } from "@paperclipai/plugin-sdk";
export const networkTools: NonNullable<PaperclipPluginManifestV1["tools"]> = [{ name: "unifi_observe_network", displayName: "Inspect company UniFi network", requiredUserPermission: "support:diagnose", executionTimeoutMs: 60000,
  description: "Read a saved company-owned UniFi site or exact device using the official local Integration API. Site returns up to 50 devices/connected clients; device returns state, firmware metadata and bounded statistics. Unavailable/partial sections stay explicit. No arbitrary endpoint, raw credentials, client MAC/IP addresses, mutations or firmware installation. Use an authorized human Clippy conversation.", parametersSchema: { type: "object", additionalProperties: false, properties: { account: { type: "string" }, siteId: { type: "string" }, operation: { type: "string", enum: ["site", "device"] }, deviceId: { type: "string" } }, required: ["account", "siteId", "operation"] } }];
const manifest: PaperclipPluginManifestV1 = {
  id: "unifi-tools", apiVersion: 1, version: "0.1.0", displayName: "UniFi Tools", description: "Scoped UniFi Network observations for staff support", author: "Paperclip Extensions contributors", categories: ["connector", "automation"],
  capabilities: ["agent.tools.register", "instance.settings.register", "http.outbound", "secrets.read-ref", "events.subscribe", "events.emit"], entrypoints: { worker: "./dist/worker.js" }, tools: networkTools,
  instanceConfigSchema: { type: "object", additionalProperties: false, properties: { accounts: { type: "array", title: "UniFi controllers", items: { type: "object", additionalProperties: false, properties: {
    key: { type: "string", title: "Account key" }, baseUrl: { type: "string", title: "Local Integration API base URL", description: "HTTPS controller URL ending in /integration (Network Server) or /proxy/network/integration (UniFi OS). Match the example in the controller's Integrations page. A trusted certificate is required; no TLS bypass." }, apiKeyRef: { type: "string", format: "secret-ref", title: "API key Secret" }, allowedCompanies: { type: "array", items: { type: "string", format: "company-id" }, title: "Allowed companies" }, sites: { type: "array", title: "Company-owned sites", items: { type: "object", additionalProperties: false, properties: { companyId: { type: "string", format: "company-id" }, siteIds: { type: "array", items: { type: "string" }, title: "Site UUIDs" } }, required: ["companyId", "siteIds"] } }, supportReadEnabled: { type: "boolean", default: false, title: "Allow Support Desk observations" }
  }, required: ["key", "baseUrl", "apiKeyRef", "allowedCompanies", "sites"] } } } },
  setupInstructions: "# UniFi setup\n\n1. Use UniFi Network's Integrations page to generate an API key and copy its local request example. This connector targets the official Network Integration API contract documented for 9.4.17; legacy undocumented /api/s/... endpoints are not used.\n2. Store the key in company Paperclip Secrets. Save its Secret reference, controller HTTPS Integration API base, allowed company and exact site UUIDs here. Match the local base to your controller's example.\n3. In authorized Clippy, call unifi_observe_network for a site. Report unavailable/partial sections. TLS must be trusted on the worker host.\n4. To use Support Desk's bridge, enable its observation option and save a Support Desk Specialist connections record with plugin key unifi-tools and this account key. Use support_check_specialist operation=site resourceId=site UUID, or operation=device resourceId=site UUID/device UUID.\n\nNo network mutations are provided in this first section. Controller version/key compatibility needs a live read pilot. Never paste the API key into Clippy or a directory note.",
};
export default manifest;
